name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
        
      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
         path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
         key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
         restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease --info --stacktrace

      - name: List APK files
        run: |
          echo "Listing APK files in the release directory..."
          ls -lh app/build/outputs/apk/release/

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: myapp
          path: app/build/myapp.apk
